import express from 'express';
import Pilgrim from '../models/Pilgrim.js';
import { body, validationResult } from 'express-validator';

const router = express.Router();

// Get family connection dashboard data
router.get('/dashboard', async (req, res) => {
  try {
    const [
      totalMessages,
      connectedFamilies,
      autoUpdates
    ] = await Promise.all([
      // Mock data - in production, get from messages collection
      Promise.resolve(247),
      Pilgrim.countDocuments({ 'familyContacts.0': { $exists: true } }),
      Promise.resolve(456) // Auto-generated messages count
    ]);

    res.json({
      messagesSent: totalMessages,
      familiesConnected: connectedFamilies,
      autoUpdates
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get recent family messages
router.get('/messages/recent', async (req, res) => {
  try {
    const { limit = 10 } = req.query;

    // Mock family messages data
    const recentMessages = [
      {
        id: '1',
        pilgrimName: 'Ahmed Al-Rashid',
        familyContact: 'Khadija Al-Rashid (Wife)',
        message: 'Alhamdulillah, I have safely reached Makkah and completed my first Tawaf. The experience is indescribable. Please keep me in your duas.',
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        status: 'delivered',
        type: 'location_update'
      },
      {
        id: '2',
        pilgrimName: 'Fatima Al-Zahra',
        familyContact: 'Ali Al-Zahra (Husband)',
        message: 'Currently in Mina for the Jamarat ritual. Everything is going smoothly, Alhamdulillah. Missing everyone at home.',
        timestamp: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
        status: 'delivered',
        type: 'status_update'
      },
      {
        id: '3',
        pilgrimName: 'Omar Ibn Khattab',
        familyContact: 'Hafsa Ibn Khattab (Daughter)',
        message: 'Baba is doing great! He just finished at Arafat and is now heading to Muzdalifah. His health is good and spirits are high.',
        timestamp: new Date(Date.now() - 135 * 60 * 1000).toISOString(),
        status: 'delivered',
        type: 'health_update'
      }
    ];

    res.json(recentMessages.slice(0, parseInt(limit)));
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Send message to family
router.post('/messages/send', [
  body('pilgrimId').notEmpty(),
  body('familyContactId').notEmpty(),
  body('message').isLength({ min: 1, max: 1000 }),
  body('type').isIn(['location_update', 'status_update', 'health_update', 'custom'])
], async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        error: 'Validation failed',
        details: errors.array()
      });
    }

    const { pilgrimId, familyContactId, message, type, autoGenerated = false } = req.body;

    // Find pilgrim
    const pilgrim = await Pilgrim.findById(pilgrimId);
    if (!pilgrim) {
      return res.status(404).json({ error: 'Pilgrim not found' });
    }

    // Find family contact
    const familyContact = pilgrim.familyContacts.id(familyContactId);
    if (!familyContact) {
      return res.status(404).json({ error: 'Family contact not found' });
    }

    // In production, you would:
    // 1. Send SMS/email via Twilio/SendGrid
    // 2. Store message in database
    // 3. Track delivery status

    const messageData = {
      id: new Date().getTime().toString(),
      pilgrimId,
      pilgrimName: pilgrim.name,
      familyContact: `${familyContact.name} (${familyContact.relationship})`,
      message,
      type,
      status: 'sent',
      timestamp: new Date().toISOString(),
      autoGenerated
    };

    // Emit real-time notification
    const io = req.app.get('io');
    io.to('operations-center').emit('family-message-notification', messageData);

    res.json({
      message: 'Message sent successfully',
      data: messageData
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Send broadcast message to all families in a group
router.post('/messages/broadcast', [
  body('groupId').notEmpty(),
  body('message').isLength({ min: 1, max: 1000 }),
  body('type').isIn(['emergency', 'general', 'weather', 'schedule'])
], async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        error: 'Validation failed',
        details: errors.array()
      });
    }

    const { groupId, message, type, priority = 'medium' } = req.body;

    // Get all pilgrims in the group
    const pilgrims = await Pilgrim.find({ groupId })
      .select('name familyContacts')
      .populate('groupId', 'name');

    if (pilgrims.length === 0) {
      return res.status(404).json({ error: 'No pilgrims found in group' });
    }

    // Collect all family contacts
    const familyMessages = [];
    pilgrims.forEach(pilgrim => {
      pilgrim.familyContacts.forEach(contact => {
        if (contact.isPrimary) { // Only send to primary contacts for broadcasts
          familyMessages.push({
            pilgrimId: pilgrim._id,
            pilgrimName: pilgrim.name,
            familyContact: `${contact.name} (${contact.relationship})`,
            contactPhone: contact.phone,
            contactEmail: contact.email,
            message,
            type,
            priority
          });
        }
      });
    });

    // In production, send messages via SMS/email service
    // For now, just simulate successful sending

    res.json({
      message: 'Broadcast message sent successfully',
      recipientCount: familyMessages.length,
      groupName: pilgrims[0].groupId.name,
      sentAt: new Date().toISOString()
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Send automatic location update to family
router.post('/messages/auto-location', [
  body('pilgrimId').notEmpty(),
  body('location').notEmpty()
], async (req, res) => {
  try {
    const { pilgrimId, location, milestone } = req.body;

    const pilgrim = await Pilgrim.findById(pilgrimId);
    if (!pilgrim) {
      return res.status(404).json({ error: 'Pilgrim not found' });
    }

    // Generate automatic message based on location/milestone
    let autoMessage = '';
    if (milestone) {
      switch (milestone) {
        case 'tawaf':
          autoMessage = `Alhamdulillah! ${pilgrim.name} has successfully completed Tawaf around the Kaaba. May Allah accept this act of worship.`;
          break;
        case 'sai':
          autoMessage = `${pilgrim.name} has completed Sa'i between Safa and Marwah. Prayers for a blessed journey ahead.`;
          break;
        case 'arafat':
          autoMessage = `${pilgrim.name} has reached the Plains of Arafat for the most important day of Hajj. Please keep them in your duas.`;
          break;
        case 'jamarat':
          autoMessage = `${pilgrim.name} has completed the stoning of Jamarat. Another milestone achieved in their spiritual journey.`;
          break;
        default:
          autoMessage = `Location update: ${pilgrim.name} is currently at ${location}. All is well, Alhamdulillah.`;
      }
    } else {
      autoMessage = `Location update: ${pilgrim.name} is currently at ${location}. All is well, Alhamdulillah.`;
    }

    // Send to all family contacts
    const sentMessages = [];
    for (const contact of pilgrim.familyContacts) {
      const messageData = {
        id: new Date().getTime().toString() + Math.random(),
        pilgrimId,
        pilgrimName: pilgrim.name,
        familyContact: `${contact.name} (${contact.relationship})`,
        message: autoMessage,
        type: 'location_update',
        status: 'sent',
        timestamp: new Date().toISOString(),
        autoGenerated: true,
        milestone
      };
      
      sentMessages.push(messageData);
    }

    // Emit real-time notifications
    const io = req.app.get('io');
    sentMessages.forEach(msg => {
      io.to('operations-center').emit('family-message-notification', msg);
    });

    res.json({
      message: 'Auto location update sent to all family members',
      messagesSent: sentMessages.length,
      milestone,
      location
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get family contact details for a pilgrim
router.get('/pilgrims/:id/contacts', async (req, res) => {
  try {
    const { id } = req.params;

    const pilgrim = await Pilgrim.findById(id)
      .select('name familyContacts');

    if (!pilgrim) {
      return res.status(404).json({ error: 'Pilgrim not found' });
    }

    res.json({
      pilgrimName: pilgrim.name,
      familyContacts: pilgrim.familyContacts
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Add family contact for a pilgrim
router.post('/pilgrims/:id/contacts', [
  body('name').notEmpty().trim(),
  body('relationship').isIn(['spouse', 'parent', 'child', 'sibling', 'other']),
  body('phone').matches(/^\+?[\d\s\-\(\)]+$/),
  body('email').optional().isEmail()
], async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        error: 'Validation failed',
        details: errors.array()
      });
    }

    const { id } = req.params;
    const { name, relationship, phone, email, isPrimary = false } = req.body;

    const pilgrim = await Pilgrim.findById(id);
    if (!pilgrim) {
      return res.status(404).json({ error: 'Pilgrim not found' });
    }

    // If this is set as primary, unset other primary contacts
    if (isPrimary) {
      pilgrim.familyContacts.forEach(contact => {
        contact.isPrimary = false;
      });
    }

    pilgrim.familyContacts.push({
      name,
      relationship,
      phone,
      email,
      isPrimary
    });

    await pilgrim.save();

    res.json({
      message: 'Family contact added successfully',
      contact: pilgrim.familyContacts[pilgrim.familyContacts.length - 1]
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get message statistics
router.get('/statistics', async (req, res) => {
  try {
    const { period = '24h' } = req.query;
    
    // Mock statistics - in production, aggregate from messages collection
    const stats = {
      totalMessages: 247,
      deliveredMessages: 243,
      failedMessages: 4,
      autoGeneratedMessages: 156,
      manualMessages: 91,
      messagesByType: {
        location_update: 89,
        status_update: 76,
        health_update: 45,
        custom: 37
      },
      averageResponseTime: '2.3 minutes',
      familySatisfactionRate: 96.8
    };

    res.json(stats);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;